
    var labels = {
                TITLE : "Sempre Esperto - Just briliant",
                NAME: "Sempre Esperto",
                JUST_HERE: "Just Here",
                JUST_NOW: "Just Now",
                JUST_BRILLIANT: "Just Brilliant",
                FIND_OUT: "Find Out Little More",
                OWN_NAME: "Stefan Abramiuk",
                OWN_ABOUT: "Owner and Founder of Sempre Esperto",
                OWN_DESC1: "Person with almost 6 years of experience in Salesforce platform.",
                OWN_DESC2: "One person who embody the role of End-to-end consultant",
                SERV_TITLE: "Services we provide",
                BUSIN_ANALYST: "Business Analyst",
                TECH_ARCH: "Technical Architect",
                DEV : "Developer",
                QA: "QA",
                PERSONALIZED : "Each design is specially personalized according to customer requirements",
                OUR_WORK: "Our Work",
                FULL_NAME : "Sempre Esperto Stefan Abramiuk",
                ADDR1: "Al. Komisji Edukacji Narodowej 36/112B",
                ADDR2: "02-797 Warszawa",
                COPYRIGHT: "Copyright \u00A9 Sempre Esperto 2016",
                ABOUT: "About",
                CONTACT: "Contact",
                HOME: "Home",
                DISCOVER: "Discover",
                COOKIE_CONSENT: "This website uses cookies for statistical, advertising and functional we provide anonymised tracking data to third party applications like Google Analytics. Thanks to them, we can customize the site to your needs. Anyone can accept cookies, or has the ability to disable them in your browser, so you will not be collected any information.",
                SEE_MORE: 'See more',
                CONFIRM: "OK",
                MORE_SOON: "More soon..."
    };