
    var labels = {
                TITLE : "Sempre Esperto - Just briliant",
                NAME: "Sempre Esperto",
                JUST_HERE: "Just Here",
                JUST_NOW: "Just Now",
                JUST_BRILLIANT: "Just Brilliant",
                FIND_OUT: "Find Out Little More",
                OWN_NAME: "Stefan Abramiuk",
                OWN_ABOUT: "Owner and Founder of Sempre Esperto",
                OWN_DESC1: "Person with almost 6 years of experience in Salesforce platform.",
                OWN_DESC2: "One person who embody the role of End-to-end consultant",
                SERV_TITLE: "Services we provide",
                BUSIN_ANALYST: "Business Analyst",
                TECH_ARCH: "Technical Architect",
                DEV : "Developer",
                QA: "QA",
                OUR_WORK: "Our Work",
                FULL_NAME : "Sempre Esperto Stefan Abramiuk",
                ADDR1: "Al. Komisji Edukacji Narodowej 36/112B",
                ADDR2: "02-797 Warszawa",
                COPYRIGHT: "Copyright \u00A9 Sempre Esperto 2016",
                ABOUT: "About",
                CONTACT: "Contact",
                HOME: "Home",
                DISCOVER: "Discover",
                COOKIE_CONSENT: "This website uses cookies for statistical, advertising and functional we provide anonymised tracking data to third party applications like Google Analytics. Thanks to them, we can customize the site to your needs. Anyone can accept cookies, or has the ability to disable them in your browser, so you will not be collected any information.",
                SEE_MORE: 'See more',
                CONFIRM: "OK",
                MORE_SOON: "More soon...",



                WHAT_WE_DO: "What do we do?",
                REQUIREMENTS: "We deliver personalized CRM applications adjusted to your needs",
                APPROACH: "We advice and help choose best possible approach",
                TRENING: "We conduct tranings (also free) in terms of CRM solutions",
                FIRST_NAME: "First Name",
                LAST_NAME: "Last Name",
                EMAIL: "Email",
                COMPANY: "Company",
                CITY: "City",
                PHONE: "Phone",
                DESCRIPTION: "Description",
                BUSIN_ANALYST_DESC: "Bazując na doświadczeniu pomagamy określić potrzeby klienta. Pozwala to na zebranie wymagań oraz zdefiniowanie zakresu projektu. Na tym etapie jesteśmy w stanie dokonać wstępnej wyceny projektu",
                TECH_ARCH_DESC: "Bazując na stworzonej dokumentacji, a także wpsaricu klienta określamy funkcjonalności dostępne w aplikacji, oraz tworzymy jej szkielet",
                DEV_DESC: "Proces tworzenia aplikacji w przypadku technologii Salesforce nie zawsze wiąże się z pisaniem kodu. Dobrze stworzona architektura pozwala dobrać najlepszą scieżkę rozwiązania problemu",
                QA_DESC: "Testowanie jest chyba jednym z najważniejszych etapów. Razem z klientam dokonujemy przeglądu wszystkich funkcjonalności aplikacji a także ich poprawnego działania",


                SALES:"Sales",
                SALES_DESC:"The #1 CRM solution takes sales force automation to new heights, with an array of cloud-based tools that give your team the power to score more wins, increase productivity, and keep the pipeline filled with solid leads. No software. No hardware. No speed limits.",
                SERVICE:"Service",
                SERVICE_DESC:"From call-center software to self-service portals, our service solutions enhance your customer service with more responsive, more intuitive, more flexible support that anticipates customer needs.",
                MARKETING:"Marketing",
                MARKETING_DESC:"Make the most of every customer interaction — creating personalized, cross-channel customer journeys that deliver exceptional brand experiences across email, mobile, social, Web, and more.",
                COMMUNITY:"Community",
                COMMUNITY_DESC:"Harness the power of social and mobile to create lively communities for rich customer engagement, employee collaboration: and alignment with resellers, partners, and distributors.",
                ANALITICS:"Analytics",
                ANALITICS_DESC:"With Analytics Cloud, drill down into any dataset, get instant answers, and collaborate with your team on any device, from anywhere. All at speeds that no other analytics solution can deliver.",
                APPS:"Apps",
                APPS_DESC:"Today every company is in the app business. App Cloud is your one-stop shop for building, running, managing, and optimizing apps using the same technology and expertise that fuels our success.",
                IOT:"Internet of Things",
                IOT_DESC:"Proactively engage your customers by connecting the internet of things with your most important customer data for more meaningful real-time actions. Connect any device, sensor, product, website, and event stream.",
                COMMERCE:"Commerce",
                COMMERCE_DESC:"Unify the customer experience across all points of commerce (web, social, mobile, store, and more) — from shopping to fulfillment to customer service — with built-in predictive intelligence that delivers a 1-to-1 shopping experience."
    };