    var labels = {
            TITLE : "Sempre Esperto - Just briliant",
            NAME: "Sempre Esperto",
            JUST_HERE: "Po prostu tutaj",
            JUST_NOW: "Po prostu teraz",
            JUST_BRILLIANT: "Po prostu genialne",
            FIND_OUT: "Dowiedz się więcej",
            OWN_NAME: "Stefan Abramiuk",
            OWN_ABOUT: "Właściciel i założyciel Sempre Esperto",
            OWN_DESC1: "Posiada prawie 6 lat doświadczenia przy pracy na platfromie Salesforce",
            OWN_DESC2: "Jedna osoba która dostarczy kompleksowe usługi w zakresie CRM",
            SERV_TITLE: "Sposób pracy",
            BUSIN_ANALYST: "Analiza wymagań",
            TECH_ARCH: "Projektowanie rozwiązania",
            DEV : "Tworzenie aplikacji",
            QA: "Testowanie",
            OUR_WORK: "Nasza praca",
            FULL_NAME : "Sempre Esperto Stefan Abramiuk",
            ADDR1: "Al. Komisji Edukacji Narodowej 36/112B",
            ADDR2: "02-797 Warszawa",
            COPYRIGHT: "Copyright \u00A9 Sempre Esperto 2016",
            ABOUT: "O mnie",
            CONTACT: "Kontakt",
            HOME: "Na górę",
            DISCOVER: "Odkrywaj",
            COOKIE_CONSENT: 'Nasza strona internetowa używa plików cookies (tzw. ciasteczka) w celach statystycznych, reklamowych oraz funkcjonalnych udostępniamy też anonimowe dane dla usług takich jak Google Analytics. Dzięki nim możemy indywidualnie dostosować stronę do twoich potrzeb. Każdy może zaakceptować pliki cookies albo ma możliwość wyłączenia ich w przeglądarce, dzięki czemu nie będą zbierane żadne informacje.',
            SEE_MORE: 'Zobacz więcej',
            CONFIRM: "OK",
            MORE_SOON: "Więcej wkrótce...",

            WHAT_WE_DO: "Czym się zajmujemy?",
            REQUIREMENTS: "Dostarczamy oprogramowanie CRM dostowane do wymagań klienta",
            APPROACH: "Doradzamy oraz pomagamy wybrać najlesze podejście",
            TRENING: "Prowadzimy szkolenia (również bezpłatne) w zakresie wykorzystania rozwiązań CRM",
            SALES:"Sales",
            SALES_DESC: "Rozwiązanie CRM nr 1 w zakresie automatyzacji sprzedaży z dostępem do szerokiej gamy narzędzi, które dają twojej drużynie moc wygrywania, zwiększenia produktywności, oraz utrzymania kolejki solidnych lead'ów. Bez oprogramowania. Bez dotakowego sprzętu. Bez limitów prędkości.",
            SERVICE:"Service",
            SERVICE_DESC:"Od oprogramowania typu call-center do portali self-service, rozwiązania sewisu poprawiają obsługę Twojego klienta lepszą dostępnością, oraz bardziej intuicyjnym podejściem, a także bardziej elastycznym wsparciem, które przewiduje potrzeby klienta.",
            MARKETING:"Marketing",
            MARKETING_DESC:"Wykorzystaj każdą interakcję z klientem - tworząc spersonalizowane, multikanałowe podróze klienta (customer journeys) które dostarczają wyjątkowe doświadczenia związane z Twoją makrą poprzez email, telefony, media społecznościowe, strony innternetowe, oraz różne inne.",
            COMMUNITY:"Community",
            COMMUNITY_DESC:"Użyj mocy mediów społecznościowych oraz urządzeń mobilnych do stworzenia żywych społeczności dla zaangażowania klientów, kolaboracji pracowników, a także współpracy sprzedawców, partnerów i dystrybutorów.",
            ANALITICS:"Analytics",
            ANALITICS_DESC:"Z narzędziem Analytics Cloud dostaniesz się do każdego potrzebnego zestawu danych. Otrzymuj natychmiastowe odpowiedzi, dziel się nimi ze swoim zespołem na każdym urządzeniu, skąd chcesz. Wszystko to z szybkością, której żadne inne analityczne narzędzie nie będzie w stanie dostarczyć.",
            APPS:"Apps",
            APPS_DESC:"Dzisiaj każda firma używa aplikacji biznesowych. App Cloud jest prostym sklepem pomagającym budować, uruchamiać, zarządzać oraz optymalizować aplikacje przy użyciu tej samej technologii i wiedzy, które jest kluczem do Twojego sukcesu.",
            IOT:"Internet of Things",
            IOT_DESC:"Proaktywnie angażuj swoich klientów podpinając Internet of Things z najważniejszymi danymi klientów dla najważniejszych działań w czasie rzeczywistym. Podłącz dowolne urządzenie, czujnik, produkt, stronę internetową oraz strumień zdarzeń.",
            COMMERCE:"Commerce",
            COMMERCE_DESC:"Zjednocz doświadczenia swoich klientów w każdym punkcie sprzedaży (strony internetowe, media społecznościowe, urządzenia mobilne, sklepy i inne) - od sprzedaży do obsługi klienta - z wbudowaną predyktywną sztuczną inteligencją która dostarcza najlepszes doświadczenia zwiazane ze sprzedażą.",
            FIRST_NAME: "Imię",
            LAST_NAME: "Nazwisko",
            EMAIL: "Email",
            COMPANY: "Firma",
            CITY: "Miasto",
            PHONE: "Numer telefonu",
            DESCRIPTION: "Opis",
            BUSIN_ANALYST_DESC: "Bazując na doświadczeniu pomagamy określić potrzeby klienta. Pozwala to na zebranie wymagań oraz zdefiniowanie zakresu projektu. Na tym etapie jesteśmy w stanie dokonać wstępnej wyceny projektu",
            TECH_ARCH_DESC: "Bazując na stworzonej dokumentacji, a także wpsaricu klienta określamy funkcjonalności dostępne w aplikacji, oraz tworzymy jej szkielet",
            DEV_DESC: "Proces tworzenia aplikacji w przypadku technologii Salesforce nie zawsze wiąże się z pisaniem kodu. Dobrze stworzona architektura pozwala dobrać najlepszą scieżkę rozwiązania problemu",
            QA_DESC: "Testowanie jest chyba jednym z najważniejszych etapów. Razem z klientam dokonujemy przeglądu wszystkich funkcjonalności aplikacji a także ich poprawnego działania"

    };