    var labels = {
            TITLE : "Sempre Esperto - Just briliant",
            NAME: "Sempre Esperto",
            JUST_HERE: "Po prostu tutaj",
            JUST_NOW: "Po prostu teraz",
            JUST_BRILLIANT: "Po prostu genialne",
            FIND_OUT: "Dowiedz się trochę więcej",
            OWN_NAME: "Stefan Abramiuk",
            OWN_ABOUT: "Właściciel i założyciel Sempre Esperto",
            OWN_DESC1: "Posiada prawie 6 lat doświadczenia przy pracy na platfromie Salesforce",
            OWN_DESC2: "Jedna osoba która dostarczy kompleksowe usługi w zakresie CRM",
            SERV_TITLE: "Usługi które mogę zaoferować",
            BUSIN_ANALYST: "Analityk Biznesowy",
            TECH_ARCH: "Architekt Techniczny",
            DEV : "Programista",
            QA: "QA",
            PERSONALIZED : "Każdy projekt jest personalizowany zgodnie z wymaganiami klienta",
            OUR_WORK: "Nasza praca",
            FULL_NAME : "Sempre Esperto Stefan Abramiuk",
            ADDR1: "Al. Komisji Edukacji Narodowej 36/112B",
            ADDR2: "02-797 Warszawa",
            COPYRIGHT: "Copyright \u00A9 Sempre Esperto 2016",
            ABOUT: "O mnie",
            CONTACT: "Kontakt",
            HOME: "Na górę",
            DISCOVER: "Odkrywaj",
            COOKIE_CONSENT: 'Nasza strona internetowa używa plików cookies (tzw. ciasteczka) w celach statystycznych, reklamowych oraz funkcjonalnych udostępniamy też anonimowe dane dla usług takich jak Google Analytics. Dzięki nim możemy indywidualnie dostosować stronę do twoich potrzeb. Każdy może zaakceptować pliki cookies albo ma możliwość wyłączenia ich w przeglądarce, dzięki czemu nie będą zbierane żadne informacje.',
            SEE_MORE: 'Zobacz więcej',
            CONFIRM: "OK",
            MORE_SOON: "Więcej wkrótce..."
    };