    var labels = {
            TITLE : "Sempre Esperto - Just briliant",
            NAME: "Sempre Esperto",
            JUST_HERE: "Po prostu tutaj",
            JUST_NOW: "Po prostu teraz",
            JUST_BRILLIANT: "Po prostu genialne",
            FIND_OUT: "Dowiedz się więcej",
            OWN_NAME: "Stefan Abramiuk",
            OWN_ABOUT: "Właściciel i założyciel Sempre Esperto",
            OWN_DESC1: "Posiada prawie 6 lat doświadczenia przy pracy na platfromie Salesforce",
            OWN_DESC2: "Jedna osoba która dostarczy kompleksowe usługi w zakresie CRM",
            SERV_TITLE: "Sposób pracy",
            BUSIN_ANALYST: "Analiza wymagań",
            BUSIN_ANALYST_DESC: "Bazując na doświadczeniu pomagamy określić potrzeby klienta. Pozwala to na zebranie wymagań oraz zdefiniowanie zakresu projektu. Na tym etapie jesteśmy w stanie dokonać wstępnej wyceny projektu",
            TECH_ARCH: "Projektowanie rozwiązania",
            TECH_ARCH_DESC: "Bazując na stworzonej dokumentacji, a także wpsaricu klienta określamy funkcjonalności dostępne w aplikacji, oraz tworzymy jej szkielet",
            DEV : "Tworzenie aplikacji",
            DEV_DESC: "Proces tworzenia aplikacji w przypadku technologii Salesforce nie zawsze wiąże się z pisaniem kodu. Dobrze stworzona architektura pozwala dobrać najlepszą scieżkę rozwiązania problemu",
            QA: "Testowanie",
            QA_DESC: "Testowanie jest chyba jednym z najważniejszych etapów. Razem z klientam dokonujemy przeglądu wszystkich funkcjonalności aplikacji a także ich poprawnego działania",
            PERSONALIZED : "Każdy projekt jest personalizowany zgodnie z wymaganiami klienta",
            OUR_WORK: "Nasza praca",
            FULL_NAME : "Sempre Esperto Stefan Abramiuk",
            ADDR1: "Al. Komisji Edukacji Narodowej 36/112B",
            ADDR2: "02-797 Warszawa",
            COPYRIGHT: "Copyright \u00A9 Sempre Esperto 2016",
            ABOUT: "O mnie",
            CONTACT: "Kontakt",
            HOME: "Na górę",
            DISCOVER: "Odkrywaj",
            COOKIE_CONSENT: 'Nasza strona internetowa używa plików cookies (tzw. ciasteczka) w celach statystycznych, reklamowych oraz funkcjonalnych udostępniamy też anonimowe dane dla usług takich jak Google Analytics. Dzięki nim możemy indywidualnie dostosować stronę do twoich potrzeb. Każdy może zaakceptować pliki cookies albo ma możliwość wyłączenia ich w przeglądarce, dzięki czemu nie będą zbierane żadne informacje.',
            SEE_MORE: 'Zobacz więcej',
            CONFIRM: "OK",
            MORE_SOON: "Więcej wkrótce...",

            WHAT_WE_DO: "Czym się zajmujemy?",
            REQUIREMENTS: "Dostarczamy oprogramowanie CRM dostowane do wymagań klienta",
            APPROACH: "Doradzamy oraz pomagamy wybrać najlesze podejście",
            TRENING: "Prowadzimy szkolenia (również bezpłatne) w zakresie wykorzystania rozwiązań CRM",
            SALES:"Sales",
            SALES_DESC:"The #1 CRM solution takes sales force automation to new heights, with an array of cloud-based tools that give your team the power to score more wins, increase productivity, and keep the pipeline filled with solid leads. No software. No hardware. No speed limits.",
            SERVICE:"Service",
            SERVICE_DESC:"From call-center software to self-service portals, our service solutions enhance your customer service with more responsive, more intuitive, more flexible support that anticipates customer needs.",
            MARKETING:"Marketing",
            MARKETING_DESC:"Make the most of every customer interaction — creating personalized, cross-channel customer journeys that deliver exceptional brand experiences across email, mobile, social, Web, and more.",
            COMMUNITY:"Community",
            COMMUNITY_DESC:"Harness the power of social and mobile to create lively communities for rich customer engagement, employee collaboration: and alignment with resellers, partners, and distributors.",
            ANALITICS:"Analytics",
            ANALITICS_DESC:"With Analytics Cloud, drill down into any dataset, get instant answers, and collaborate with your team on any device, from anywhere. All at speeds that no other analytics solution can deliver.",
            APPS:"Apps",
            APPS_DESC:"Today every company is in the app business. App Cloud is your one-stop shop for building, running, managing, and optimizing apps using the same technology and expertise that fuels our success.",
            IOT:"Internet of Things",
            IOT_DESC:"Proactively engage your customers by connecting the internet of things with your most important customer data for more meaningful real-time actions. Connect any device, sensor, product, website, and event stream.",
            COMMERCE:"Commerce",
            COMMERCE_DESC:"Unify the customer experience across all points of commerce (web, social, mobile, store, and more) — from shopping to fulfillment to customer service — with built-in predictive intelligence that delivers a 1-to-1 shopping experience.",
            FIRST_NAME: "Imię",
            LAST_NAME: "Nazwisko",
            EMAIL: "Email",
            COMPANY: "Firma",
            CITY: "Miasto",
            PHONE: "Numer telefonu",
            DESCRIPTION: "Opis"
    };